Add psp-gdb instruction
pspdev/psplinkusb pull request #34
Opened 2023-07-15 04:50 UTC by diamant3

Here's my PR for #22, it's ready for review @sharkwouter @sajattack

2023-07-15 08:45 UTC, sharkwouter requested changes
Thanks for doing this, I really appreciate it!

I found a couple of small wording issues and some sentences which were a bit yoo long, but good work on this otherwise. Looks almost ready for merging 😄

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Prepare a separate terminal for `usbhostfs_pc`, `pspsh` and `psp-gdb`. All of them are needed to point the directory location to your `.prx` and `.elf` files located or the file you need to debug.
```suggestion
Prepare a separate terminal for `usbhostfs_pc`, `pspsh` and `psp-gdb`. Open all of them in the directory in which your compiled `.prx` and `.elf` files are located.
```

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Prepare a separate terminal for `usbhostfs_pc`, `pspsh` and `psp-gdb`. All of them are needed to point the directory location to your `.prx` and `.elf` files located or the file you need to debug.
I'm not sure if this suggestion makes sense, since pspsh does noy need to be opened in a specific directory.

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Run `usbhostfs_pc` on your terminal dedicated for `usbhostfs_pc` and you will see the `waiting for device...` status and then start the PSPLINK app on your PSP and connect the USB cable, you will see
```suggestion
Run `usbhostfs_pc` on your terminal dedicated for `usbhostfs_pc` and you will see the `waiting for device...` status. Now start the PSPLINK app on your PSP and connect the USB cable. You should see the `connected to device` status in the terminal, which means success. Do not close this terminal after that.
```

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Run `usbhostfs_pc` on your terminal dedicated for `usbhostfs_pc` and you will see the `waiting for device...` status and then start the PSPLINK app on your PSP and connect the USB cable, you will see
Not sure if this suggestion is the best wording, but the long sentence would be nice to break up.

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Run `pspsh` on your terminal dedicated for `pspsh` and you will see the `host0:/>`. After that you need to change again the directory where your files needed to debug. lastly, run `debug <file.prx>`
You probably won't need to change directory. It will open where you ran usbhostfs_pc

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Run `pspsh` on your terminal dedicated for `pspsh` and you will see the `host0:/>`. After that you need to change again the directory where your files needed to debug. lastly, run `debug <file.prx>`
I would remove <> from the debug command for clarity

2023-07-15 08:45 UTC, sharkwouter commented on README.md
> +Run `psp-gdb <file.elf> -q` on your terminal dedicated for `psp-gdb` and you will see something like this:
The elf file has no extension, but has the same name as the prx otherwise. Might want to clarify that.

2023-07-15 14:01 UTC, diamant3 commented
Done! @sharkwouter

2023-07-15 20:56 UTC, sharkwouter approved these changes

2023-07-15 20:56 UTC, merged

2023-07-15 20:57 UTC, sharkwouter commented
Thanks!

2023-07-16 00:30 UTC, sajattack commented
Sorry I didn't get to this

2023-07-16 01:37 UTC, diamant3 commented
It's okay. Let me know in the discord if there are any suggestions or changes you need me to make